general_configuration:
  img_size: [256, 256]
  valid_extensions: [".bmp", ".BMP"]
features_extractor:
  backbone: "wide_resnet50_2"
  weights: "DEFAULT"
  folder_map:
    'D:/emanuele/Code/eda_dataset/data/good': "Good"
    'D:/emanuele/Code/eda_dataset/data/reject': "Reject"

